### ISSUE TITLE
arcade

### ISSUE THREAD

**Issue by gringoDiaz** [dojwun/arcade#1]
everything is good and working i just experience some issue can u help me? when i start a game i cant exit or turn of the game

**Comment by dojwun** [comment]
make sure the file name is rcore_arcade

**Comment by dojwun** [comment]
yeah i can add an item check so it wont spam your inventory with items soon

**Comment by gringoDiaz** [comment]
Thanks man appreciate ur effort! <3

**Comment by dojwun** [comment]
alright man just updated it, mostly server side
